version: "3"

services:
  staffshare-loadbalancer:
    container_name: staffshare-loadbalancer
    restart: always
    build:
      context: ./loadbalancer
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ${PWD}/loadbalancer/nginx:/etc/nginx/:rw
    depends_on:
      - staffshare-api
      - staffshare-web
    networks:
      - staffshare

  staffshare-api:
    container_name: staffshare-api
    restart: always
    environment:
      - DB_NAME=staffshare
      - STAFFSHARE_SERVER_PORT=5000
      - MONGODB_URI=mongodb://staffshare-db:27017/staffshare
      - STAFFSHARE_SERVER_ADDR=0.0.0.0
    build:
      context: ./backend-python
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/backend-python:/app/staffshare-api:rw
    ports:
      - "5000:5000"

    depends_on:
      - staffshare-db
    networks:
      - staffshare

  staffshare-web:
    container_name: staffshare-web
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/frontend:/app:rw
    ports:
      - "3000:3000"
    depends_on:
      - staffshare-db
    environment:
      - NEXT_PUBLIC_API_URL=https://test.staffshare.co
      - NEXTAUTH_URL=https://test.staffshare.co
      - NEXTAUTH_SECRET=${STAFFSHARE_NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${STAFFSHARE_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${STAFFSHARE_GOOGLE_CLIENT_SECRET}
    networks:
      - staffshare

  staffshare-db:
    container_name: staffshare-db
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - staffshare
  
  staffshare-db-ui:
    container_name: staffshare-db-ui
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
    networks:
      - staffshare

networks:
  staffshare:
    driver: bridge
